defaultEntryPoints = ["http", "https"]

[entryPoints]
 [entryPoints.http]
 address = ":80"
 compress = false
 [entryPoints.https]
 address = ":443"
 compress = false

[ping]

[api]
dashboard = true

[accessLog]
logLevel = "INFO"

[docker]
domain="docker.localhost"
watch=true
swarmmode=true
endpoint="unix:///var/run/docker.sock"